### PR TITLE
fix: use VerifyReader to verify read content after oras.Fetch

### LINKED ISSUE #547: Need verify rc against the descriptor after calling oras.Fetch()
When reading from the io.ReadCloser returned by `oras.Fetch()` function, it's recommended to verify the read content against the descriptor. 
We could use the utility method from ORAS-GO to do the verification after https://github.com/oras-project/oras-go/issues/306 being resolved.

reference: 
`desc, rc, err := oras.Fetch(ctx, src, opts.targetRef, oras.FetchOptions{})`
https://github.com/oras-project/oras/pull/520#discussion_r965650328

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
Resolves #547 

Signed-off-by: wangxiaoxuan273 <wangxiaoxuan119@gmail.com>

### CODE REVIEW

File: cmd/oras/blob/fetch.go [hunk 1]
```diff
@@ -114,6 +116,14 @@ func fetchBlob(opts fetchBlobOptions) (fetchErr error) {
 		// fetch blob content
 		var rc io.ReadCloser
 		desc, rc, err = oras.Fetch(ctx, src, opts.targetRef, oras.DefaultFetchOptions)
+		vr := content.NewVerifyReader(rc, desc)
+		buf := bytes.NewBuffer(nil)
+		if _, err := io.Copy(buf, vr); err != nil {
+			return err
+		}
```
Comment (shizhMSFT) [inline cmd/oras/blob/fetch.go:123]: Blobs are usually large and cannot be dumped into memory.

**Review by shizhMSFT — CHANGES_REQUESTED** [review]

File: cmd/oras/blob/fetch.go (hunk 1 above)
Comment (wangxiaoxuan273) [reply cmd/oras/blob/fetch.go]: Fixed according to our offline discussion.

**Review by shizhMSFT — APPROVED** [review]
LGTM
