### PR TITLE
fix: allow HTTPS for localhost

### LINKED ISSUE #1106: oras tries to use http instead of https
### What happened in your environment?

When executing command `oras repo ls localhost`
I get this error:
```
Error: Get "http://localhost/v2/_catalog": dial tcp [::1]:80: connect: connection refused
```

There is no argument for using https, only for using http (`--plain-http`), so what's going wrong?

### What did you expect to happen?

_No response_

### How can we reproduce it?

.

### What is the version of your ORAS CLI?

Version:    1.1.0+Homebrew
Go version: go1.21.0

### What is your OS environment?

MacOS

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

### PR DESCRIPTION
**Pull request by qweeah**
**What this PR does / why we need it**:
This PR allows user to specify `--plain-http=false` for a registry named `localhost`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1106 

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

File: cmd/oras/internal/option/remote.go [hunk 1]
```diff
@@ -43,7 +43,6 @@ import (
 // Remote options struct.
 type Remote struct {
 	CACertFilePath    string
-	PlainHTTP         bool
```
Comment (shizhMSFT) [inline cmd/oras/internal/option/remote.go:46]: How about changing it to
```go
PlainHTTP func() (plainHTTP bool, enforced bool)
```

File: cmd/oras/internal/option/remote.go [hunk 2]
```diff
@@ -98,7 +98,15 @@ func (opts *Remote) ApplyFlagsWithPrefix(fs *pflag.FlagSet, prefix, description
 	fs.StringVarP(&opts.Username, flagPrefix+"username", shortUser, "", notePrefix+"registry username")
 	fs.StringVarP(&opts.Password, flagPrefix+"password", shortPassword, "", notePrefix+"registry password or identity token")
 	fs.BoolVarP(&opts.Insecure, flagPrefix+"insecure", "", false, "allow connections to "+notePrefix+"SSL registry without certs")
-	fs.BoolVarP(&opts.PlainHTTP, flagPrefix+"plain-http", "", false, "allow insecure connections to "+notePrefix+"registry without SSL check")
+	plainHTTPFlagName := flagPrefix + "plain-http"
+	plainHTTP := false
+	fs.BoolVar(&plainHTTP, plainHTTPFlagName, plainHTTP, "allow insecure connections to "+notePrefix+"registry without SSL check")
```
Comment (shizhMSFT) [inline cmd/oras/internal/option/remote.go:103]: Consider `fs.Bool` instead of `fs.BoolVar`.

File: cmd/oras/internal/option/remote.go [hunk 3]
```diff
@@ -305,9 +313,12 @@ func (opts *Remote) NewRepository(reference string, common Common, logger logrus
...
 func (opts *Remote) isPlainHttp(registry string) bool {
+	if plainHTTP := opts.getPlainHTTP(); plainHTTP != nil {
+		return *plainHTTP
+	}
 	host, _, _ := net.SplitHostPort(registry)
 	if host == "localhost" || registry == "localhost" {
 		return true
 	}
-	return opts.PlainHTTP
+	return false
```
Comment (shizhMSFT) [inline cmd/oras/internal/option/remote.go:323]: This code can be simplified as `return host == "localhost" || registry == "localhost"`

File: cmd/oras/internal/option/remote.go [hunk 4]
```diff
@@ -305,9 +309,11 @@ func (opts *Remote) NewRepository(reference string, common Common, logger logrus
...
-	if host == "localhost" || registry == "localhost" {
-		return true
+	if plainHTTP, enforced := opts.plainHTTP(); enforced {
+		return plainHTTP
 	}
-	return opts.PlainHTTP
+
+	// not specified, defaults to plain http for localhost
+	host, _, _ := net.SplitHostPort(registry)
+	return host == "localhost" || registry == "localhost"
```
Comment (shizhMSFT) [inline cmd/oras/internal/option/remote.go:318]: This part seems not right.

Should it be
```suggestion
	// not specified, defaults to plain http for localhost
	host, _, _ := net.SplitHostPort(registry)
	if host == "localhost" || registry == "localhost" {
		return true
	}
	return plainHTTP
```
?

**Review by shizhMSFT — APPROVED** [review]
LGTM
