### PR TITLE
fix: missing status for pull

### LINKED ISSUE #527: UI bug: pull status missing if two files have identical content
Suppose we have below artifact store in the repository `localhost:5000/oras:debug`
```
               +----------+     +--------+
               | Manifest +-----> config |
               +--+----+--+     +--------+
                  |    |
Annotation Title:foo  Annotation Title:bar
                  |    |
              +---v----v---+
              | Layer Blob |
              +------------+
```
Pulling the below artifact with command `oras pull localhost:5000/oras:debug -v`, the log will be like
```
Skipped     e3b0c44298fc application/vnd.unknown.config.v1+json
Downloading b5bb9d8014a0 bar
Downloaded  b5bb9d8014a0 bar
Downloading 87dd1ad58716 application/vnd.oci.image.manifest.v1+json
Downloaded  87dd1ad58716 application/vnd.oci.image.manifest.v1+json
Pulled localhost:5000/oras:debug
Digest: sha256:87dd1ad58716fb216620b4d28ead9b7d68911e0339cca658cfc2b371c27a0d40
```
Although indeed `foo` and `bar` are both pulled, in the UI there is no hit for downloading `foo`.

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
Resolves #527 

Signed-off-by: wangxiaoxuan273 <wangxiaoxuan119@gmail.com>

### CODE REVIEW

File: cmd/oras/pull.go [hunk 1]
```diff
@@ -135,7 +135,7 @@ func runPull(opts pullOptions) error {
 				}
 				// Skip s if s is unnamed and has no successors.
 				if len(ss) == 0 {
-					if _, loaded := printed.LoadOrStore(s.Digest.String(), true); !loaded {
+					if _, loaded := printed.LoadOrStore(display.Name(s), true); !loaded {
```
Comment (qweeah) [inline cmd/oras/pull.go:138]: @wangxiaoxuan273 Will `desc.Digest.String() + desc.Annotations[ocispec.AnnotationTitle]` work?

File: cmd/oras/pull.go [hunk 2]
```diff
@@ -161,14 +181,10 @@ func runPull(opts pullOptions) error {
 			// named content downloaded
 			pulledEmpty = false
 		}
+		printed.LoadOrStore(display.Name(desc), true)
```
Comment (qweeah) [inline cmd/oras/pull.go:184]: What is the purpose of this line? Why the returned values are ignored?

File: cmd/oras/pull.go [hunk 3]
```diff
@@ -148,9 +148,29 @@ func runPull(opts pullOptions) error {
...
+		}
+		for _, s := range ss {
+			exists, _ := dst.Exists(ctx, s)
+			if exists {
+				if _, loaded := printed.LoadOrStore(display.Name(s), true); !loaded {
+					if err = display.PrintStatus(s, "Restored   ", opts.Verbose); err != nil {
+						return err
+					}
+				}
+			}
```
Comment (qweeah) [inline cmd/oras/pull.go:172]: The missing else block here means: a manifest is pulled but one of its successor is not, which is a big SDK error and should be handled.

File: cmd/oras/pull.go (hunk 2 above)
Comment (qweeah) [reply cmd/oras/pull.go:184]: Should use https://pkg.go.dev/sync#Map.Store here

File: cmd/oras/pull.go [hunk 4]
```diff
@@ -148,9 +148,29 @@ func runPull(opts pullOptions) error {
...
 	pulledEmpty := true
 	copyOptions.PreCopy = display.StatusPrinter("Downloading", opts.Verbose)
 	copyOptions.PostCopy = func(ctx context.Context, desc ocispec.Descriptor) error {
+		// restore successors, if applicable
+		ss, err := content.Successors(ctx, dst, desc)
+		if err != nil {
+			return err
+		}
+		for _, s := range ss {
+			exists, _ := dst.Exists(ctx, s)
```
Comment (qweeah) [inline cmd/oras/pull.go:165]: if `desc.Annotations[ocispec.AnnotationTitle]` is not presented, then `desc` won't be downloaded to `dst`. I think that should be used here instead of `.Exists`

File: cmd/oras/pull.go (hunk 1 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go:138]: Yes it worked. Replaced with `desc.Digest.String() + desc.Annotations[ocispec.AnnotationTitle]`.

File: cmd/oras/pull.go (hunk 2 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go:184]: Changed to `sync.Map.Store`

File: cmd/oras/pull.go (hunk 3 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go:171]: This `exists` check is removed per the next comment, so this comment is resolved.

File: cmd/oras/pull.go (hunk 4 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go]: replaced the `exists` check with `_, ok := s.Annotations[ocispec.AnnotationTitle]`.

File: cmd/oras/pull.go [hunk 5]
```diff
@@ -135,7 +135,7 @@ func runPull(opts pullOptions) error {
 				}
 				// Skip s if s is unnamed and has no successors.
 				if len(ss) == 0 {
-					if _, loaded := printed.LoadOrStore(s.Digest.String(), true); !loaded {
+					if _, loaded := printed.LoadOrStore(s.Digest.String()+s.Annotations[ocispec.AnnotationTitle], true); !loaded {
```
Comment (qweeah) [inline cmd/oras/pull.go:138]: let's make a private function for this with `s` as input

File: cmd/oras/pull.go [hunk 6]
```diff
@@ -148,9 +148,28 @@ func runPull(opts pullOptions) error {
...
+
 	pulledEmpty := true
 	copyOptions.PreCopy = display.StatusPrinter("Downloading", opts.Verbose)
 	copyOptions.PostCopy = func(ctx context.Context, desc ocispec.Descriptor) error {
+		// restore named successors, if applicable
+		successors, err := content.Successors(ctx, dst, desc)
+		if err != nil {
+			return err
+		}
+		for _, successor := range successors {
```
Comment (qweeah) [inline cmd/oras/pull.go:164]: Nit: `s` is enough
```suggestion
		for _, s:= range successors {
```

Comment (wangxiaoxuan273) [reply cmd/oras/pull.go:164]: renamed it to `s`.

File: cmd/oras/pull.go (hunk 5 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go:138]: Added a function `generateKey(desc ocispec.Descriptor)`.

**Review by qweeah — APPROVED** [review]
LGTM

File: cmd/oras/pull.go [hunk 7]
```diff
@@ -148,9 +148,28 @@ func runPull(opts pullOptions) error {
...
 
+	ctx, _ := opts.SetLoggerLevel()
+	var dst = file.New(opts.Output)
+	dst.AllowPathTraversalOnWrite = opts.PathTraversal
+	dst.DisableOverwrite = opts.KeepOldFiles
+
 	pulledEmpty := true
 	copyOptions.PreCopy = display.StatusPrinter("Downloading", opts.Verbose)
 	copyOptions.PostCopy = func(ctx context.Context, desc ocispec.Descriptor) error {
+		// restore named successors, if applicable
```
Comment (qweeah) [inline cmd/oras/pull.go:159]:
```suggestion
		// restore named but deduplicated successor nodes
```

File: cmd/oras/pull.go [hunk 8]
```diff
@@ -185,3 +200,7 @@ func runPull(opts pullOptions) error {
 func isManifestMediaType(mediaType string) bool {
 	return mediaType == docker.MediaTypeManifest || mediaType == ocispec.MediaTypeImageManifest
 }
+
+func generateKey(desc ocispec.Descriptor) string {
```
Comment (shizhMSFT) [inline cmd/oras/pull.go:204]: Can we have a more meaningful name other than `generateKey`? Meanwhile, can we document this method so that others can understand easily?

File: cmd/oras/pull.go [hunk 9]
```diff
@@ -148,9 +148,28 @@ func runPull(opts pullOptions) error {
...
 	copyOptions.PreCopy = display.StatusPrinter("Downloading", opts.Verbose)
 	copyOptions.PostCopy = func(ctx context.Context, desc ocispec.Descriptor) error {
+		// restore named but deduplicated successor nodes
+		successors, err := content.Successors(ctx, dst, desc)
+		if err != nil {
+			return err
+		}
+		for _, s := range successors {
+			if _, ok := s.Annotations[ocispec.AnnotationTitle]; ok {
+				if _, ok := printed.Load(generateKey(s)); !ok {
```
Comment (shizhMSFT) [inline cmd/oras/pull.go:166]: Curious on the reason why we use `Load` over `LoadOrStore`.

@wangxiaoxuan273 @qweeah Could you explain a bit?

Comment (qweeah) [reply cmd/oras/pull.go:166]: Printed is for deduplication. File target has already done the deduplication since it won't allow duplidated filename, not mentioning duplicated digest+filename.

File: cmd/oras/pull.go (hunk 8 above)
Comment (qweeah) [reply cmd/oras/pull.go:204]: How about `namedDigest`?

Comment (wangxiaoxuan273) [reply cmd/oras/pull.go]: Changed to name` generateDeduplicatedMapKey` and added a doc comment.

**Review by shizhMSFT — APPROVED** [review]
LGTM

File: cmd/oras/pull.go (hunk 8 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go]: Changed to name `generateContentKey` and added a doc comment.

File: cmd/oras/pull.go (hunk 9 above)
Comment (wangxiaoxuan273) [reply cmd/oras/pull.go]: Changed back to `LoadOrStore`.
