### PR TITLE
test: add E2E specs for `oras blob push`

### LINKED ISSUE #587: e2e: add test specs for `oras blob push` command
Happy paths:
- should push a blob from stdin
- should push a blob from a file
- should push a blob from a file and output the descriptor
- progress status should be disabled when --descriptor is provided
- should show preview hint in help doc

Bad paths:
- should fail if no blob file reference is provided
- should fail directly if not logged in

### PR DESCRIPTION
**Pull request by qweeah**
This PR relies on merging of #700

Resolves #587

### CODE REVIEW

File: test/e2e/internal/utils/file.go [hunk 1]
```diff
@@ -21,6 +21,8 @@ import (
 	"regexp"
 	"time"
 
+	. "github.com/onsi/ginkgo/v2"
+	"github.com/onsi/gomega"
 	. "github.com/onsi/gomega"
```
Comment (shizhMSFT) [inline test/e2e/internal/utils/file.go:26]: Looks like they are duplicated

File: test/e2e/internal/utils/file.go [hunk 2]
```diff
@@ -63,6 +65,15 @@ func MatchFile(filepath string, want string, timeout time.Duration) {
 	Eventually(gbytes.BufferReader(f)).WithTimeout(timeout).Should(gbytes.Say(want))
 }
 
+// WriteTempFile writes content into name under a temp folder.
+func WriteTempFile(name string, content string) (path string) {
+	tempDir := GinkgoT().TempDir()
+	path = filepath.Join(tempDir, name)
+	err := os.WriteFile(path, []byte(content), 0777)
```
Comment (shizhMSFT) [inline test/e2e/internal/utils/file.go:72]: `0666` is better than `0777`.

File: test/e2e/suite/command/blob.go [hunk 3]
```diff
@@ -14,19 +14,78 @@ limitations under the License.
...
-	"os"
+	"fmt"
 	"path/filepath"
+	"strconv"
+	"strings"
 
 	. "github.com/onsi/ginkgo/v2"
-	. "github.com/onsi/gomega"
-	"github.com/onsi/gomega/gbytes"
+
```
Comment (shizhMSFT) [inline test/e2e/suite/command/blob.go:23]: nit: remove empty line

File: test/e2e/suite/command/blob.go [hunk 4]
```diff
@@ -14,19 +14,78 @@ limitations under the License.
...
 	. "oras.land/oras/test/e2e/internal/utils"
 )
 
+var pushContent = "test-blob"
+var pushLength = strconv.Itoa(len(pushContent))
+var pushDigest = "sha256:e1ca41574914ba00e8ed5c8fc78ec8efdfd48941c7e48ad74dad8ada7f2066d8"
+var wrongDigest = "sha256:e1ca41574914ba00e8ed5c8fc78ec8efdfd48941c7e48ad74dad8ada7f2066d9"
+var pushDescFmt = `{"mediaType":"%s","digest":"sha256:e1ca41574914ba00e8ed5c8fc78ec8efdfd48941c7e48ad74dad8ada7f2066d8","size":9}`
+var repoFmt = fmt.Sprintf("command/blob/push/%d/%%s", GinkgoRandomSeed())
```
Comment (shizhMSFT) [inline test/e2e/suite/command/blob.go:32]: some of them can be const?

**Review by shizhMSFT — APPROVED** [review]
LGTM
