### PR TITLE
fix: fix error message when output is used before format for oras discover

### LINKED ISSUE #1348: `oras discover` shows wrong error message
### What happened in your environment?

If `--output` and `--format` are used at the same time, flag confliction error is output
```console
> oras discover localhost:7000/demo:eol --format "{{.manifests}}" --output json
[DEPRECATED] --output is deprecated, try `--format json` instead
Error: if any flags in the group [output format] are set none of the others can be; [format output] were all set
```

But if the `--output` flag is used before `--format`, wrong error output is shown:
```console
> oras discover localhost:7000/demo:eol --output json --format "{{.manifests}}"
Error: output type can only be tree, table or json
```

### What did you expect to happen?

Should always show error message that both flags cannot be used at the same time

### How can we reproduce it?

Run below command
```console
oras discover localhost:7000/demo:eol --output json --format "{{.manifests}}"
```

### What is the version of your ORAS CLI?

Main branch build from https://github.com/oras-project/oras/commit/fa65f61c86fa75b23b8f2afffe1ba77a5fbf44b7

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1348 

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [x]  Do all new files have an appropriate license header?

### CODE REVIEW

File: cmd/oras/internal/errors/errors.go [hunk 1]
```diff
@@ -159,25 +159,17 @@ func NewErrEmptyTagOrDigest(ref string, cmd *cobra.Command, needsTag bool) error
...
-// the rest of the flag sets.
-func CheckMutuallyExclusiveFlags(fs *pflag.FlagSet, exclusiveFlagSets ...[]string) error {
-	var checkConflict = func(exclusiveFlagSet []string) []string {
-		changedFlags := []string{}
-		for _, flagName := range exclusiveFlagSet {
-			if fs.Changed(flagName) {
-				changedFlags = append(changedFlags, fmt.Sprintf("--%s", flagName))
-			}
+// at the same time, returns an error when detecting used exclusive flags.
+func CheckMutuallyExclusiveFlags(fs *pflag.FlagSet, exclusiveFlagSet []string) error {
```
Comment (shizhMSFT) [inline cmd/oras/internal/errors/errors.go:163]: nit: you may consider
```suggestion
func CheckMutuallyExclusiveFlags(fs *pflag.FlagSet, exclusiveFlagSet ...string) error {
```

**Review by shizhMSFT — APPROVED** [review]
LGTM with suggestions
