### PR TITLE
fix(ut): fix flaky console tests

### LINKED ISSUE #1543: flaky console test
### What happened in your environment?

Sometimes when running the unit test, the console test might fail unexpectedly with error
```console
> go test -count=20 ./...                                           
...
ok      oras.land/oras/cmd/oras/internal/display/status 0.080s
--- FAIL: TestConsole_OutputTo (0.00s)
    console_test.go:112: OutputTo output error: failed to find "^[8^[[1Ftest string^[[0m\r\n^[[0K" in ""
FAIL
FAIL    oras.land/oras/cmd/oras/internal/display/status/console 0.073s
ok  
```

### What did you expect to happen?

The test should pass

### How can we reproduce it?

Run all unit tests with high repetition count, e.g. 20, and it's likely to happen

```bash
go test -count=20 ./...            
``` 

### What is the version of your ORAS CLI?

Main branch build in 5280c67fcef9e1029d539aef03370a31e5df839a

### What is your OS environment?

Ubuntu 24.04

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

### PR DESCRIPTION
**Pull request by qweeah**
**What this PR does / why we need it**:
This PR fixes flaky console unit tests. To reproduce the flaky tests, try
```bash
go test -count=1000 -run ^TestConsole_Save$ oras.land/oras/cmd/oras/internal/display/status/console
```
PTY output might be interrupted by unexpected error like ` console_test.go:134: Save output error: failed to find "^[[?25l^[7^[[0m" in ""`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1543

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

File: cmd/oras/internal/display/status/console/console_test.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func TestConsole_NewRow(t *testing.T) {
 
 	c.NewRow()
 
-	err := testutils.MatchPty(pty, tty, "^[8\r\n^[7")
+	err := testutils.MatchPty(pty, tty, "\x1b8\r\n\x1b7")
```
Comment (Wwwsylvia) [inline cmd/oras/internal/display/status/console/console_test.go:99]: Just a non-blocking question, how does the fix work? 🧐

Comment (TerryHowe) [reply cmd/oras/internal/display/status/console/console_test.go:99]: The old code is ascii control character and the new code is the escape sequence for that characters which is better IMO..
