### PR TITLE
fix: oras push should return error when artifacttype is empty for spec 1.1

### LINKED ISSUE #1313: avoid pushing artifacts without `artifactType` if `--image-spec v1.1` is specified
### What is the version of your ORAS CLI

v1.2.0

### What would you like to be added?

`oras push` supports pushing an artifact without `artifactType` even when OCI image spec v1.1 is specified.
```console
➜  ~ oras push localhost:5000/artifact:type --format json --config <(echo -n "{}"):my/type --image-spec v1.1
✓ Exists    my/type                                                                                0/0  B 100.00%     0s
  └─ sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
✓ Exists    application/vnd.oci.empty.v1+json                                                      2/2  B 100.00%     0s
  └─ sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
✓ Uploaded  application/vnd.oci.image.manifest.v1+json                                         442/442  B 100.00%     0s
  └─ sha256:3179007d443a6c79a5e3b8af868cf762202ca3e95ecf87da456e59963913e006
{
  "Ref": "localhost:5000/artifact@sha256:3179007d443a6c79a5e3b8af868cf762202ca3e95ecf87da456e59963913e006",
  "MediaType": "application/vnd.oci.image.manifest.v1+json",
  "Digest": "sha256:3179007d443a6c79a5e3b8af868cf762202ca3e95ecf87da456e59963913e006",
  "Size": 442,
  "Annotations": {
    "org.opencontainers.image.created": "2024-03-28T01:43:28Z"
  },
  "ArtifactType": ""
}
➜  ~ oras manifest fetch --pretty localhost:5000/artifact:type
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "my/type",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 0
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.empty.v1+json",
      "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
      "size": 2,
      "data": "e30="
    }
  ],
  "annotations": {
    "org.opencontainers.image.created": "2024-03-28T01:43:28Z"

```

### Why is this needed for ORAS?

According to [the guidance](https://github.com/opencontainers/image-spec/blob/0d530f4f36d7cdefd985b201630551e61ba604d9/manifest.md?plain=1#L172), v1.1 artifact should always contains an `artifactType`, so 
1) ` --config` MUST not to be used with `--image-spec v1.1` if `--artifac-type` is not specified, return error when encounter this.
2) `--image-spec` should be default to `auto`, which represents `v1.0` if `--config` is used and `--artifact-type` not used. Otherwise `v1.1`

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
**What this PR does / why we need it**:
`oras push` should return an error when `--config` is used, `--artifact-type` is not used and `--image-spec` is set to `v1.1`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1313 

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [x]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

**Comment by wangxiaoxuan273** [comment]
There are 2 issues to discuss:
1. Do we allow users to input `--image-spec auto`? (currently yes)
2. What should be the output of `oras push -h` for `--image-spec`? (current display below) 
Screenshot 2024-04-02 at 15 08 57

File: cmd/oras/root/push.go [hunk 1]
```diff
@@ -108,6 +108,16 @@ Example - Push file "hi.txt" into an OCI image layout folder 'layout-dir' with t
 			if err := option.Parse(cmd, &opts); err != nil {
 				return err
 			}
+
+			if opts.manifestConfigRef != "" && opts.artifactType == "" {
+				switch opts.Flag {
+				case option.ImageSpecAuto:
+					opts.PackVersion = oras.PackManifestVersion1_0
```
Comment (qweeah) [inline cmd/oras/root/push.go:115]: Better explain why we need to switch here, e.g. here packs an artifact that is not compliant to OCI artifact guidance https://github.com/opencontainers/image-spec/blob/e7f7c0ca69b21688c3cea7c87a04e4503e6099e2/manifest.md?plain=1#L170

File: test/e2e/suite/command/push.go [hunk 2]
```diff
@@ -233,6 +243,28 @@ var _ = Describe("Remote registry users:", func() {
...
+				WithWorkDir(tempDir).Exec()
+			// validate
+			fetched := ORAS("manifest", "fetch", RegistryRef(ZOTHost, repo, tag)).Exec().Out.Contents()
+			var manifest ocispec.Manifest
+			Expect(json.Unmarshal(fetched, &manifest)).ShouldNot(HaveOccurred())
+			Expect(manifest.Config).Should(Equal(ocispec.Descriptor{
+				MediaType: configType,
+				Size:      int64(foobar.FileConfigSize),
+				Digest:    foobar.FileConfigDigest,
+			}))
```
Comment (qweeah) [inline test/e2e/suite/command/push.go:265]: Should confirm that `manifest.Artifact` is not set

File: test/e2e/suite/command/push.go [hunk 3]
```diff
@@ -233,6 +243,28 @@ var _ = Describe("Remote registry users:", func() {
 			}))
 		})
 
+		It("should pack with image spec v1.0 when --config is used, --artifact-type is not used, and --image-spec set to auto", func() {
+			repo := pushTestRepo("my/test/repo")
```
Comment (qweeah) [inline test/e2e/suite/command/push.go:247]: Better name after the test case, e.g. `config/without/artifact/type`

File: test/e2e/suite/command/push.go [hunk 4]
```diff
@@ -102,6 +102,16 @@ var _ = Describe("ORAS beginners:", func() {
 				MatchErrKeyWords("Error:", invalidFlag, "Available options: v1.1, v1.0").
 				Exec()
 		})
+
+		It("should fail if image spec v1.1 is used, with --config and without --artifactType", func() {
+			testRepo := attachTestRepo("test-repo")
```
Comment (qweeah) [inline test/e2e/suite/command/push.go:107]: Wrong utility method used. Also the repo name should be related to the test case, e.g. `v1-1/no-artifact-type`
```suggestion
			testRepo := pushTestRepo("test-repo")
```

File: cmd/oras/internal/option/spec.go [hunk 5]
```diff
@@ -67,19 +68,21 @@ func (is *ImageSpec) Options() string {
...
 func (is *ImageSpec) String() string {
-	return is.flag
+	return is.Flag
 }
 
 // ApplyFlags applies flags to a command flag set.
 func (is *ImageSpec) ApplyFlags(fs *pflag.FlagSet) {
-	// default to v1.1-rc.4
+	// default to auto
+	defaultFlag := ImageSpecAuto
```
Comment (qweeah) [inline cmd/oras/internal/option/spec.go:83]: remove the default flag and assign `ImageSpecAuto` directly

**Review by qweeah — CHANGES_REQUESTED** [review]

File: test/e2e/suite/command/push.go (hunk 2 above)
Comment (wangxiaoxuan273) [reply test/e2e/suite/command/push.go:265]: Added this confirmation in Line 266

File: cmd/oras/root/push.go (hunk 1 above)
Comment (wangxiaoxuan273) [reply cmd/oras/root/push.go:117]: added a comment

File: cmd/oras/root/push.go [hunk 6]
```diff
@@ -108,6 +108,21 @@ Example - Push file "hi.txt" into an OCI image layout folder 'layout-dir' with t
 			if err := option.Parse(cmd, &opts); err != nil {
 				return err
 			}
+
+			if opts.manifestConfigRef != "" && opts.artifactType == "" {
+				// Here packs an artifact that is not compliant to OCI artifact guidance.
+				// Reference: https://github.com/opencontainers/image-spec/blob/e7f7c0ca69b21688c3cea7c87a04e4503e6099e2/manifest.md?plain=1#L170
+				switch opts.Flag {
+				case option.ImageSpecAuto:
+					opts.PackVersion = oras.PackManifestVersion1_0
```
Comment (qweeah) [inline cmd/oras/root/push.go:117]:
```suggestion
				switch opts.Flag {
				case option.ImageSpecAuto:
					// switch to v1.0 manifest since artifact type is suggested by OCI v1.1 artifact guidance but not presented 
					// see https://github.com/opencontainers/image-spec/blob/e7f7c0ca69b21688c3cea7c87a04e4503e6099e2/manifest.md?plain=1#L170
					opts.PackVersion = oras.PackManifestVersion1_0
```

File: cmd/oras/root/push.go [hunk 7]
```diff
@@ -108,6 +108,22 @@ Example - Push file "hi.txt" into an OCI image layout folder 'layout-dir' with t
...
+			if opts.manifestConfigRef != "" && opts.artifactType == "" {
+				switch opts.Flag {
+				case option.ImageSpecAuto:
+					// switch to v1.0 manifest since artifact type is suggested by OCI v1.1
+					// artifact guidance but is not presented
+					// see https://github.com/opencontainers/image-spec/blob/e7f7c0ca69b21688c3cea7c87a04e4503e6099e2/manifest.md?plain=1#L170
+					opts.PackVersion = oras.PackManifestVersion1_0
+				case option.ImageSpecV1_1:
+					return &oerrors.Error{
+						Err:            errors.New(`artifact type missing for OCI v1.1 artifacts`),
```
Comment (shizhMSFT) [inline cmd/oras/root/push.go:121]:
```suggestion
						Err:            errors.New(`artifact type missing for OCI image-spec v1.1 artifacts`),
```

File: cmd/oras/root/push.go [hunk 8]
```diff
@@ -108,6 +108,22 @@ Example - Push file "hi.txt" into an OCI image layout folder 'layout-dir' with t
...
+						Recommendation: "set an artifact type via `--artifact-type` or use v1.0 image spec",
```
Comment (shizhMSFT) [inline cmd/oras/root/push.go:122]:
```suggestion
						Recommendation: "set an artifact type via `--artifact-type` or consider image spec v1.0",
```

File: cmd/oras/root/push.go [hunk 9]
```diff
@@ -108,6 +108,22 @@ Example - Push file "hi.txt" into an OCI image layout folder 'layout-dir' with t
...
+			if opts.manifestConfigRef != "" && opts.artifactType == "" {
+				switch opts.Flag {
+				case option.ImageSpecAuto:
+					// switch to v1.0 manifest since artifact type is suggested by OCI v1.1
+					// artifact guidance but is not presented
+					// see https://github.com/opencontainers/image-spec/blob/e7f7c0ca69b21688c3cea7c87a04e4503e6099e2/manifest.md?plain=1#L170
+					opts.PackVersion = oras.PackManifestVersion1_0
+				case option.ImageSpecV1_1:
+					return &oerrors.Error{
+						Err:            errors.New(`artifact type missing for OCI image-spec v1.1 artifacts`),
```
Comment (shizhMSFT) [inline cmd/oras/root/push.go:121]:
```suggestion
						Err:            errors.New(`missing artifact type for OCI image-spec v1.1 artifacts`),
```

**Review by shizhMSFT — APPROVED** [review]
LGTM with suggestions

**Review by qweeah — APPROVED** [review]
lgtm
