### PR TITLE
test(e2e): update spec-related constants to string literal

### LINKED ISSUE #721: e2e: update spec-related constants to string literal
So when the spec is updated, the breaking change can be reflected explicitly in failed E2E tests. Bump PR should also include E2E fix.

### PR DESCRIPTION
**Pull request by qweeah**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #721 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

File: test/e2e/internal/testdata/multi_arch/const.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ var (
 	LinuxAMD64ReferrerStateKey       = match.StateKey{Digest: "57e6462826c8", Name: "application/vnd.oci.image.manifest.v1+json"}
 	LinuxAMD64ReferrerConfigStateKey = match.StateKey{Digest: "44136fa355b3", Name: "referrer.image"}
 	LinuxAMD64StateKeys              = []match.StateKey{
-		{Digest: "9d84a5716c66", Name: ocispec.MediaTypeImageManifest},
+		{Digest: "9d84a5716c66", Name: "application/vnd.oci.image.manifest.v1+json"},
 		{Digest: "fe9dbc99451d", Name: ocispec.MediaTypeImageConfig},
```
Comment (shizhMSFT) [inline test/e2e/internal/testdata/multi_arch/const.go:67]: Do we need to replace it?

**Review by shizhMSFT — APPROVED** [review]
LGTM
