### PR TITLE
fix: resolve duplicated debug log for `oras cp`

### LINKED ISSUE #1096: Bug: Unexpected request number in `--debug` log
### What happened in your environment?

The `--debug` log for `oras cp` sometimes display duplicated request number (e.g. two Request `#0`). It looks like the request number is counted per repository. 
I think this behavior is confusing and misleading. 
```text
repo1 #0
repo2 #0
repo1 #1
repo2 #1
```

#### Command
```sh
oras cp localhost:8080/testcount_1:v1 localhost:8080/testcount_2:v1 --debug 2>debug.log
```

#### Logs
```log
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #0
> Request URL: "http://localhost:8080/v2/testcount_1/manifests/v1"
> Request method: "GET"
> Request headers:
   "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.oci.artifact.manifest.v1+json"
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #0
< Response Status: "200 OK"
< Response headers:
   "Access-Control-Allow-Origin": "*"
   "Content-Length": "985"
   "Content-Type": "application/vnd.oci.image.manifest.v1+json"
   "Docker-Content-Digest": "sha256:fd6c245fe6a450b3cc7cd0229ff0963409ed28498c0f45c98766ed0d7853e965"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #0
> Request URL: "http://localhost:8080/v2/testcount_2/manifests/sha256:fd6c245fe6a450b3cc7cd0229ff0963409ed28498c0f45c98766ed0d7853e965"
> Request method: "HEAD"
> Request headers:
   "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.oci.artifact.manifest.v1+json"
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #0
< Response Status: "404 Not Found"
< Response headers:
   "Access-Control-Allow-Origin": "*"
   "Content-Type": "application/json"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
   "Content-Length": "283"
   "Access-Control-Allow-Headers": "Authorization,content-type,X-ZOT-API-CLIENT"
   "Access-Control-Allow-Methods": "HEAD,GET,OPTIONS"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #2
> Request URL: "http://localhost:8080/v2/testcount_2/blobs/sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
> Request method: "HEAD"
> Request headers:
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #3
> Request URL: "http://localhost:8080/v2/testcount_2/blobs/sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c"
> Request method: "HEAD"
> Request headers:
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #1
> Request URL: "http://localhost:8080/v2/testcount_2/blobs/sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730"
> Request method: "HEAD"
> Request headers:
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #2
< Response Status: "200 OK"
< Response headers:
   "Accept-Ranges": "bytes"
   "Content-Length": "2"
   "Docker-Content-Digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #4
> Request URL: "http://localhost:8080/v2/testcount_2/blobs/sha256:bf07a7fbb825fc0aae7bf4a1177b2b31fcf8a3feeaf7092761e18c859ee52a9c"
> Request method: "HEAD"
> Request headers:
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #3
< Response Status: "200 OK"
< Response headers:
   "Accept-Ranges": "bytes"
   "Content-Length": "4"
   "Docker-Content-Digest": "sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #1
< Response Status: "200 OK"
< Response headers:
   "Accept-Ranges": "bytes"
   "Content-Length": "4"
   "Docker-Content-Digest": "sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #4
< Response Status: "200 OK"
< Response headers:
   "Accept-Ranges": "bytes"
   "Content-Length": "4"
   "Docker-Content-Digest": "sha256:bf07a7fbb825fc0aae7bf4a1177b2b31fcf8a3feeaf7092761e18c859ee52a9c"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #5
> Request URL: "http://localhost:8080/v2/testcount_2/manifests/v1"
> Request method: "PUT"
> Request headers:
   "Content-Type": "application/vnd.oci.image.manifest.v1+json"
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #5
< Response Status: "201 Created"
< Response headers:
   "Docker-Content-Digest": "sha256:fd6c245fe6a450b3cc7cd0229ff0963409ed28498c0f45c98766ed0d7853e965"
   "Location": "/v2/testcount_2/manifests/sha256:fd6c245fe6a450b3cc7cd0229ff0963409ed28498c0f45c98766ed0d7853e965"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"
   "Content-Length": "0"
time=2023-08-31T11:02:36+08:00 level=debug msg=Request #6
> Request URL: "http://localhost:8080/v2/testcount_2/manifests/sha256:fd6c245fe6a450b3cc7cd0229ff0963409ed28498c0f45c98766ed0d7853e965"
> Request method: "GET"
> Request headers:
   "Accept": "application/vnd.oci.image.manifest.v1+json"
   "User-Agent": "oras/1.1.0-rc.2"
time=2023-08-31T11:02:36+08:00 level=debug msg=Response #6
< Response Status: "200 OK"
< Response headers:
   "Access-Control-Allow-Origin": "*"
   "Content-Length": "985"
   "Content-Type": "application/vnd.oci.image.manifest.v1+json"
   "Docker-Content-Digest": "sha256:fd6c245fe6a450b3cc7cd0229ff0963409ed28498c0f45c98766ed0d7853e965"
   "Date": "Thu, 31 Aug 2023 03:02:36 GMT"

```

### What did you expect to happen?

It'd be better to merge the two counts into a single count, so that the request number becomes:
```text
repo1 #0
repo2 #1
repo1 #2
repo2 #3
```

### How can we reproduce it?

Run
```sh
oras cp $myregistry1/$myrepo:$mytag $myregistry2/$myrepo:$mytag --debug 2>debug.log
```
against any two remote repositories.

### What is the version of your ORAS CLI?

```sh
Version:        1.1.0-rc.2
Go version:     go1.21.0
Git commit:     443242e41d469a911af6fa68f3338fcfb2f5f268
Git tree state: clean
```

### What is your OS environment?

Ubuntu 18.04.4

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

### PR DESCRIPTION
**Pull request by qweeah**
**What this PR does / why we need it**:
This PR fixes a bug that causes duplicated numbering for debug logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1096

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

File: test/e2e/suite/command/cp.go [hunk 1]
```diff
@@ -80,6 +79,15 @@ var _ = Describe("1.1 registry users:", func() {
 			CompareRef(src, dst)
 		})
 
+		It("should copy and show debug logs with duplication", func() {
```
Comment (Wwwsylvia) [inline test/e2e/suite/command/cp.go:82]: nit: without duplication? Or something like "should copy and track request number per target"?

File: internal/trace/transport.go [hunk 2]
```diff
@@ -22,11 +22,12 @@ import (
 	"sync/atomic"
 )
 
+var count uint64
```
Comment (shizhMSFT) [inline internal/trace/transport.go:25]: Since `count` is a global variable now, how about naming it as `requestCount`?
Meanwhile, could you write documentation for it?

Comment (qweeah) [reply internal/trace/transport.go]: renamed & doc added

File: test/e2e/suite/command/cp.go (hunk 1 above)
Comment (qweeah) [reply test/e2e/suite/command/cp.go]: Trying to say deduplication here, rephrased.

File: internal/trace/transport.go [hunk 3]
```diff
@@ -38,13 +41,13 @@
...
 func (t *Transport) RoundTrip(req *http.Request) (resp *http.Response, err error) {
-	number := atomic.AddUint64(&t.count, 1) - 1
+	id := atomic.AddUint64(&requestCount, 1) - 1
 	ctx := req.Context()
 	e := Logger(ctx)
 
 	// log the request
 	e.Debugf("Request #%d\n> Request URL: %q\n> Request method: %q\n> Request headers:\n%s",
-		number, req.URL, req.Method, logHeader(req.Header))
+		id, req.URL, req.Method, logHeader(req.Header))
```
[the remark this answers is not in the document]
Comment (Wwwsylvia) [reply internal/trace/transport.go:50]: Interesting

[the remark this answers is not in the document]
Comment (wangxiaoxuan273) [reply internal/trace/transport.go:50]: we dismissed it [last time](https://github.com/oras-project/oras/pull/861).

[the remark this answers is not in the document]
Comment (TerryHowe) [reply internal/trace/transport.go:50]: Does `logHeader` do an redactions?

File: internal/trace/transport.go [hunk 4]
```diff
@@ -22,11 +22,14 @@ import (
 	"sync/atomic"
 )
 
+// requestCount records the number of logged request-response pairs and will
+// be used as the unique id for the next pair.
+var requestCount uint64
```
Comment (wangxiaoxuan273) [inline internal/trace/transport.go:27]: nit: do we need to reset the variable's value back to zero, when we are done with the counting? Currently it's not necessary, it's a package level variable and we may need it in the future.

**Review by shizhMSFT — APPROVED** [review]
LGTM
