### PR TITLE
fix: ignore --pretty when --output is used for oras manifest fetch

### LINKED ISSUE #1361: `--pretty` should not prettify file output
### What happened in your environment?

If `oras manifest fetch` is used with `--pretty` set and `--output` set to a file, then the output file is prettified

### What did you expect to happen?

According to the help doc, `--pretty` should only prettify stdout output
>  --pretty                                      prettify JSON objects printed to stdout

### How can we reproduce it?

```shell
 oras manifest fetch -o out mcr.microsoft.com/oss/kubernetes/kubectl:v1.31.0-alpha.0 --platform linux/amd64 --pretty
```
The saved file `out` will be prettified.

### What is the version of your ORAS CLI?

Version:        1.2.0-beta.1+unreleased
Go version:     go1.22.1
Git commit:     fa65f61c86fa75b23b8f2afffe1ba77a5fbf44b7
Git tree state: dirty

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1361 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

File: cmd/oras/root/manifest/fetch.go [hunk 1]
```diff
@@ -74,8 +74,10 @@ Example - Fetch raw manifest from an OCI layout archive file 'layout.tar':
 			switch {
 			case opts.outputPath == "-" && opts.Template != "":
 				return fmt.Errorf("`--output -` cannot be used with `--format %s` at the same time", opts.Template)
-			case opts.OutputDescriptor && opts.outputPath == "-":
+			case opts.outputPath == "-" && opts.OutputDescriptor:
 				return fmt.Errorf("`--descriptor` cannot be used with `--output -` at the same time")
+			case opts.outputPath != "" && opts.Pretty.Pretty:
```
Comment (qweeah) [inline cmd/oras/root/manifest/fetch.go:79]:
```suggestion
			case opts.outputPath != "" && opts.outputPath != "-"  && opts.Pretty.Pretty:
```

Comment (qweeah) [reply cmd/oras/root/manifest/fetch.go:79]: Also need a comment in the case block, e.g. `--pretty only effects stdout output`

**Review by qweeah — APPROVED** [review]
LGTM
