### PR TITLE
fix: bring back `--verbose` flag

### LINKED ISSUE #1640: --verbose flag removed in oras 1.3.0-beta.2
### What happened in your environment?

The ```--verbose flag``` was removed in 1.3.0-beta.2:

Image

In previous versions (e.g. 1.1.0) it used to work:

Image

### What did you expect to happen?

```--verbose``` should continue to work in version 1.3.0-beta.2.

### How can we reproduce it?

Try to use any subcommand with the ```--verbose``` flag.

### What is the version of your ORAS CLI?

Version:        1.3.0-beta.2
Go version:     go1.24.0
OS/Arch:        darwin/amd64
Git commit:     87379d22f42b5132ed583587766f0a780f9bd322
Git tree state: clean

### What is your OS environment?

Mac OS Sonoma (14.7.2)

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
**What this PR does / why we need it**:

This PR brings back the `--verbose` flag to the following commands and mark it as deprecated.

oras blob delete
oras blob fetch
oras login
oras manifest delete
oras manifest fetch
oras manifest fetch-config
oras repo ls
oras repo tags
oras resolve
oras tag

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1640 

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

File: cmd/oras/root/login.go [hunk 1]
```diff
@@ -73,6 +75,8 @@ Example - Log in with username and password in an interactive terminal and no TL
 			return runLogin(cmd, opts)
 		},
 	}
+	cmd.Flags().BoolVarP(&opts.verbose, "verbose", "v", true, "print status output for unnamed blobs")
```
Comment (Wwwsylvia) [inline cmd/oras/root/login.go:78]: nit: Although the description is hidden, how about making the description simply "verbose output"? The original description looks a bit misleading in code.

**Review by Wwwsylvia — APPROVED** [review]
LGTM with nit

File: cmd/oras/root/login.go (hunk 1 above)
Comment (wangxiaoxuan273) [reply cmd/oras/root/login.go:78]: Thanks for catching! It should be "verbose output", I forgot to change the description when pasting.

**Review by Wwwsylvia — APPROVED** [review]
LGTM

File: cmd/oras/root/blob/delete.go [hunk 2]
```diff
@@ -37,6 +37,8 @@ type deleteBlobOptions struct {
 	option.Descriptor
 	option.Pretty
 	option.Target
+	// Deprecated: verbose is deprecated and will be removed in the future.
```
Comment (TerryHowe) [inline cmd/oras/root/blob/delete.go:40]: Didn't @shizhMSFT make a comment in a previous PR about not commenting private members? That potentially would apply here as well.

File: cmd/oras/root/blob/delete.go [hunk 3]
```diff
@@ -69,6 +71,8 @@ Example - Delete a blob and print its descriptor:
 		},
 	}
 
+	cmd.Flags().BoolVarP(&opts.verbose, "verbose", "v", true, "verbose output")
+	_ = cmd.Flags().MarkDeprecated("verbose", "and will be removed in a future release.")
```
Comment (shizhMSFT) [inline cmd/oras/root/blob/delete.go:75]: Can we refactor it out? Since the verbose variable completely has no effect, can we just point it to nowhere?

We can have a quick discuss offline for the trick.

**Review by shizhMSFT — CHANGES_REQUESTED** [review]

File: cmd/oras/root/blob/delete.go (hunk 2 above)
Comment (wangxiaoxuan273) [reply cmd/oras/root/blob/delete.go]: removed this field after refactoring

File: cmd/oras/root/blob/delete.go (hunk 3 above)
Comment (wangxiaoxuan273) [reply cmd/oras/root/blob/delete.go]: refactored after offline discussion

**Review by Wwwsylvia — APPROVED** [review]
LGTM

File: cmd/oras/internal/option/verbose.go [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+*/
+
+package option
+
+import "github.com/spf13/pflag"
+
+// AddDeprecatedVerboseFlag adds the deprecated verbose flag to a command
+func AddDeprecatedVerboseFlag(flags *pflag.FlagSet) {
+	// ignoring the variable of the verbose flag, since we will not use it
+	_ = flags.BoolP("verbose", "v", true, "verbose output")
```
[the remark this answers is not in the document]
Comment (wangxiaoxuan273) [reply cmd/oras/internal/option/verbose.go]: Updated

**Review by shizhMSFT — APPROVED** [review]
LGTM
